[package]
name = "jsonrpc-rabbitmq"
description = "Rust RabbitMQ transport server"
version = "9.0.0"
license = "MIT"

[dependencies]
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-2.2" }
serde = "1.0"
serde_json = "1.0"
