[package]
name = "sha2_compression"
version = "0.6.0"
authors = ["The RustCrypto Devs"]
license = "MIT/Apache-2.0"
description = "SHA-2 hash functions"
documentation = "https://docs.rs/sha2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.6"
generic-array = "0.8"
byte-tools = "0.2"
block-buffer = "0.2"
fake-simd = "0.1"
sha2-asm = {version="0.3", optional=true}

[dev-dependencies]
crypto-tests = "0.5"

[features]
asm = ["sha2-asm"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
