version: 2
defaults: &defaults
  working_directory: ~/parity
  docker:
    - image: circleci/rust:latest

jobs:
  test:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run the tests
          command: |
            mkdir -p ~/.ssh/
            /usr/bin/ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            sudo apt update
            sudo apt upgrade -y
            sudo apt install time build-essential libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev \
            liblz4-dev libzstd-dev perl python libsnappy1v5 libudev-dev cmake libgflags-dev linux-headers-amd64 -y
            RUST_BACKTRACE=1 ./test.sh
          no_output_timeout: 30m
  deploy_docker_image:
    <<: *defaults
    docker:
      - image: docker/compose:1.23.0
    environment:
      FINAL_IMAGE: registry.dev.infra.chronicled.com/blockchain-interface
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: cargo-docker-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - /caches/parity-image.tar
      - run: 
          name: Setup Docker credentials
          command: mkdir -p ~/.docker; echo -n "${REGISTRY_AUTH}" > ~/.docker/config.json;
      - run:
          name: Load Docker image layer cache
          command: |
            if [ -f /caches/parity-image.tar ]; then docker load -i /caches/parity-image.tar; fi
      - run:
          name: Build docker image
          command: |
            export SHORT_COMMIT="$(echo $CIRCLE_SHA1 | cut -c1-7)";
            export PREV_IMAGE=`docker images "${FINAL_IMAGE}" --format "{{.Repository}}:{{.Tag}}" | head -n 1`;
            docker build --rm=false -f scripts/docker/alpine/Dockerfile --tag "${FINAL_IMAGE}:${SHORT_COMMIT}" . --cache-from="${PREV_IMAGE}";
      - run:
          name: Deploy to dockerhub
          command: |
            SHORT_COMMIT="$(echo $CIRCLE_SHA1 | cut -c1-7)";
            docker push "${FINAL_IMAGE}:${SHORT_COMMIT}";
            docker logout;
      - run:
          name: Save docker image layers for next build
          command: |
            export SHORT_COMMIT="$(echo $CIRCLE_SHA1 | cut -c1-7)" ;
            mkdir -p /caches;
            if [ ! -f /caches/parity-image.tar ]; then docker save -o /caches/parity-image.tar "${FINAL_IMAGE}:${SHORT_COMMIT}"; fi
      - save_cache:
          key: cargo-docker-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - /caches/parity-image.tar

workflows:
  version: 2
  blockchain-interface-workflow:
    jobs:
      - test
      - deploy_docker_image:
          requires:
            - test
          filters:
            branches:
              only: chronicled-develop
